### ISSUE TITLE
AMD P-State is available

### ISSUE THREAD

**Issue by AlexMV12** [milkovsky/Linux-on-Lenovo-Slim-7-Carbon-AMD#4]
Hello,

First all, thanks Milkovsky! I really was looking for a place to share the problems of this laptop with Linux.
I have to say that I hope all of these things get solved, because the laptop itself is great.

I just wanted to highlight that we can use AMD P-State with kernel 5.17+, as it is written in this ArchWiki page (about a similar model): https://wiki.archlinux.org/title/Lenovo_IdeaPad_5_Pro_14ACN6#AMD_P-State

I am using it, it is early to say if it is better than the default one, but maybe it can be useful for other users.
Thanks!

**Comment by milkovsky** [comment]
Thank you for sharing!
I added this to the readme: https://github.com/milkovsky/Linux-on-Lenovo-Slim-7-Carbon-AMD/blob/main/README.md#amd-p-state
